/// Biomechanics metric selector for per-exercise rep counting.
enum ExerciseMetricKind {
  squat,
  pushUp,
  lunge,
  deadlift,
  shoulderPress,
  pullUp,
  benchPress,
  chestFly,
  latPulldown,
  seatedRow,
  legCurl,
  hipThrust,
  gluteBridge,
  stepUp,
  lateralRaise,
  frontRaise,
  facePull,
  bicepsCurl,
  dips,
  cableCrunch,
  legRaise,
}
