import 'package:camera/camera.dart';

import '../engine/adaptive_rep_engine.dart';
import 'exercise_profile.dart';
import 'exercise_tracking_mode.dart';
import 'pose_frame.dart';

abstract final class ExerciseProfilesData {
  static const _hipLeg = [
    PoseLandmark.leftHip,
    PoseLandmark.rightHip,
    PoseLandmark.leftKnee,
    PoseLandmark.rightKnee,
    PoseLandmark.leftAnkle,
    PoseLandmark.rightAnkle,
  ];

  static const _upperBody = [
    PoseLandmark.leftShoulder,
    PoseLandmark.rightShoulder,
    PoseLandmark.leftElbow,
    PoseLandmark.rightElbow,
    PoseLandmark.leftWrist,
    PoseLandmark.rightWrist,
  ];

  static const _fullBody = [..._upperBody, ..._hipLeg];

  static const _defaultRep = AdaptiveRepEngineConfig(
    defaultBottom: 95,
    defaultTop: 155,
    hysteresisBand: 10,
    minRomSpan: 25,
  );

  static const _elbowRep = AdaptiveRepEngineConfig(
    defaultBottom: 90,
    defaultTop: 155,
    hysteresisBand: 8,
    minBottomDwellMs: 100,
  );

  static const _abductionRep = AdaptiveRepEngineConfig(
    defaultBottom: 35,
    defaultTop: 95,
    hysteresisBand: 8,
    minRomSpan: 22,
  );

  static final Map<String, ExerciseProfile> byId = {
    'bench_press': _profile(
      id: 'bench_press',
      orientation: CameraOrientationHint.side,
      placement:
          'Place the phone on a bench or rack at chest height, 2–3 m to your side.',
      framing: 'Side view: shoulders, elbows, and wrists visible during the press.',
      safety: 'Keep feet planted; do not bounce the bar off the chest.',
      steps: [
        'Lie on the bench with the bar over your chest.',
        'Turn your side toward the camera (left or right profile).',
        'Keep the full arm path in frame from shoulder to wrist.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'chest_fly': _profile(
      id: 'chest_fly',
      orientation: CameraOrientationHint.front,
      placement: 'Set the phone in front of you at shoulder height, 2–3 m away.',
      framing: 'Front view: both arms opening wide and closing in front of the chest.',
      safety: 'Use a controlled arc; avoid locking elbows aggressively.',
      steps: [
        'Stand or lie with arms out to the sides.',
        'Face the camera directly.',
        'Raise arms to shoulder height before each rep.',
      ],
      joints: _upperBody,
      rep: _abductionRep,
    ),
    'push_ups': _profile(
      id: 'push_ups',
      orientation: CameraOrientationHint.side,
      placement: 'Phone low on the floor, 2 m to your side, at hip height.',
      framing: 'Side view: shoulders, elbows, hips, and ankles in one line.',
      safety: 'Keep a straight plank line; lower under control.',
      steps: [
        'Start in a high plank.',
        'Turn your side to the camera.',
        'Lower until the elbow bends clearly, then press up.',
      ],
      joints: _fullBody,
      rep: _elbowRep,
    ),
    'pull_ups': _profile(
      id: 'pull_ups',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front of the bar, 2–3 m away, at chin height.',
      framing: 'Front view: shoulders, elbows, wrists, and chin visible.',
      safety: 'No kipping; full controlled range.',
      steps: [
        'Hang under the bar facing the camera.',
        'Pull until elbows bend and chin rises toward hands.',
        'Lower back to a full hang between reps.',
      ],
      joints: [..._upperBody, PoseLandmark.nose],
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 95,
        defaultTop: 150,
        hysteresisBand: 10,
        minEccentricVelocity: 25,
      ),
    ),
    'lat_pulldown': _profile(
      id: 'lat_pulldown',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front of the machine, chest height, 2–3 m away.',
      framing: 'Front view: upper body and both arms through the pull.',
      safety: 'Pull elbows down; avoid shrugging.',
      steps: [
        'Sit facing the camera.',
        'Start with arms extended overhead.',
        'Pull the handle to the upper chest each rep.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'seated_row': _profile(
      id: 'seated_row',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side at shoulder height, 2 m from the seat.',
      framing: 'Side view: elbow bending as you pull toward the torso.',
      safety: 'Keep the spine tall; squeeze shoulder blades.',
      steps: [
        'Sit with your profile toward the camera.',
        'Arms extended at the start of each rep.',
        'Pull elbows back past the torso.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'deadlift': _profile(
      id: 'deadlift',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, hip height, 2–3 m away.',
      framing: 'Side view: shoulders, hips, and knees through the hinge.',
      safety: 'Neutral spine; bar stays close to the legs.',
      steps: [
        'Stand with profile to the camera.',
        'Hinge at the hips with soft knees.',
        'Stand tall at the top of each rep.',
      ],
      joints: [
        PoseLandmark.leftShoulder,
        PoseLandmark.rightShoulder,
        PoseLandmark.leftHip,
        PoseLandmark.rightHip,
        PoseLandmark.leftKnee,
        PoseLandmark.rightKnee,
      ],
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 105,
        defaultTop: 165,
        hysteresisBand: 9,
        minRomSpan: 22,
      ),
    ),
    'squats': _profile(
      id: 'squats',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at hip height, 2–3 m away, full body in frame.',
      framing: 'Front view: hips, knees, and ankles visible through the squat.',
      safety: 'Knees track over toes; chest stays up.',
      steps: [
        'Stand facing the camera, feet shoulder-width.',
        'Sit hips back and down until thighs are parallel or lower.',
        'Drive up to standing for each rep.',
      ],
      joints: _hipLeg,
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 95,
        defaultTop: 155,
        hysteresisBand: 10,
        minEccentricVelocity: 20,
        minRomSpan: 30,
      ),
    ),
    'lunges': _profile(
      id: 'lunges',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at hip height, 2–3 m away.',
      framing: 'Front view: both legs visible as you step forward and back.',
      safety: 'Front knee over ankle; torso upright.',
      steps: [
        'Face the camera.',
        'Step forward into a lunge, then return to stand.',
        'Alternate legs or complete one side per set.',
      ],
      joints: _hipLeg,
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 95,
        defaultTop: 160,
        hysteresisBand: 10,
        minRomSpan: 28,
      ),
    ),
    'leg_curl': _profile(
      id: 'leg_curl',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to the side of the machine, knee height, 2 m away.',
      framing: 'Side view: knee bending as the heel moves toward the glutes.',
      safety: 'Keep hips on the pad; curl smoothly.',
      steps: [
        'Lie or kneel on the leg curl machine, side to camera.',
        'Start with the leg almost straight.',
        'Curl until the knee is clearly bent, then lower.',
      ],
      joints: _hipLeg,
      rep: _defaultRep,
    ),
    'hip_thrust': _profile(
      id: 'hip_thrust',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, hip height, 2 m from the bench.',
      framing: 'Side view: hips rising from bench to full extension.',
      safety: 'Tuck ribs; drive through heels.',
      steps: [
        'Upper back on the bench, profile to camera.',
        'Lower hips toward the floor.',
        'Drive hips up and squeeze glutes at the top.',
      ],
      joints: _hipLeg,
      rep: _defaultRep,
    ),
    'glute_bridge': _profile(
      id: 'glute_bridge',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, floor level, 2 m away.',
      framing: 'Side view: hips lifting off the floor.',
      safety: 'Pause briefly at the top; avoid over-arching the lower back.',
      steps: [
        'Lie on your back, knees bent, side to camera.',
        'Lift hips until shoulders–hips–knees align.',
        'Lower hips with control.',
      ],
      joints: _hipLeg,
      rep: _defaultRep,
    ),
    'romanian_deadlift': _profile(
      id: 'romanian_deadlift',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, hip height, 2–3 m away.',
      framing: 'Side view: hip hinge with slight knee bend.',
      safety: 'Keep the weight close; feel stretch in hamstrings.',
      steps: [
        'Stand profile to camera, soft knees.',
        'Push hips back, lowering the weight along the legs.',
        'Return to standing by driving hips forward.',
      ],
      joints: [
        PoseLandmark.leftShoulder,
        PoseLandmark.rightShoulder,
        PoseLandmark.leftHip,
        PoseLandmark.rightHip,
        PoseLandmark.leftKnee,
        PoseLandmark.rightKnee,
      ],
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 105,
        defaultTop: 165,
        hysteresisBand: 9,
        minRomSpan: 22,
      ),
    ),
    'step_up': _profile(
      id: 'step_up',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front, full body visible, 2–3 m away.',
      framing: 'Front view: front leg stepping onto the box and standing tall.',
      safety: 'Press through the whole front foot; avoid pushing off the back leg only.',
      steps: [
        'Face the camera with the box beside you.',
        'Step up with one leg until standing on the box.',
        'Step down with control; switch legs as needed.',
      ],
      joints: _hipLeg,
      rep: _defaultRep,
    ),
    'shoulder_press': _profile(
      id: 'shoulder_press',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at chest height, 2–3 m away.',
      framing: 'Front view: both arms pressing overhead.',
      safety: 'Brace core; press without excessive back arch.',
      steps: [
        'Stand or sit facing the camera.',
        'Start with hands at shoulder height.',
        'Press overhead until arms are extended.',
      ],
      joints: _upperBody,
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 90,
        defaultTop: 155,
        hysteresisBand: 12,
        minEccentricVelocity: 18,
      ),
    ),
    'lateral_raise': _profile(
      id: 'lateral_raise',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at shoulder height, 2–3 m away.',
      framing: 'Front view: arms lifting out to the sides.',
      safety: 'Soft elbows; stop at shoulder height.',
      steps: [
        'Stand facing the camera, arms at sides.',
        'Raise arms to the sides until parallel to the floor.',
        'Lower with control.',
      ],
      joints: _upperBody,
      rep: _abductionRep,
    ),
    'front_raise': _profile(
      id: 'front_raise',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at shoulder height, 2–3 m away.',
      framing: 'Front view: arms lifting forward to shoulder height.',
      safety: 'No swinging; lift with control.',
      steps: [
        'Face the camera, arms at thighs.',
        'Raise arms forward to shoulder height.',
        'Lower slowly.',
      ],
      joints: _upperBody,
      rep: _abductionRep,
    ),
    'face_pull': _profile(
      id: 'face_pull',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at face height, 2–3 m away.',
      framing: 'Front view: elbows pulling back toward the face.',
      safety: 'Keep elbows high; squeeze rear delts.',
      steps: [
        'Face the camera, cable at chest height.',
        'Start with arms extended.',
        'Pull handles toward the face with elbows wide.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'biceps_curl': _profile(
      id: 'biceps_curl',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at waist height, 2 m away.',
      framing: 'Front view: elbows at sides, forearms curling up.',
      safety: 'Keep elbows fixed; no body swing.',
      steps: [
        'Stand facing the camera.',
        'Arms extended at the bottom.',
        'Curl until hands near shoulders.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'hammer_curl': _profile(
      id: 'hammer_curl',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front at waist height, 2 m away.',
      framing: 'Front view: neutral-grip curl with elbows at sides.',
      safety: 'Control the lowering phase.',
      steps: [
        'Face the camera, palms facing each other.',
        'Start with arms straight.',
        'Curl without moving elbows forward.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'dips': _profile(
      id: 'dips',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, chest height, 2 m from bars.',
      framing: 'Side view: elbows bending behind the torso.',
      safety: 'Lower only to a comfortable depth.',
      steps: [
        'Support on bars, profile to camera.',
        'Lower until elbows are about 90°.',
        'Press back to straight arms.',
      ],
      joints: _upperBody,
      rep: _elbowRep,
    ),
    'plank': ExerciseProfile(
      id: 'plank',
      mode: ExerciseTrackingMode.holdBased,
      preferredLens: CameraLensDirection.front,
      orientationHint: CameraOrientationHint.side,
      placementHint: 'Phone on the floor to your side, 2 m away, at hip height.',
      framingHint: 'Side view: straight line from shoulders through hips to ankles.',
      safetyNote: 'Stop if you feel lower-back discomfort.',
      setupSteps: [
        'Get into a forearm or high plank.',
        'Turn your side toward the camera.',
        'Hold still with glutes and core engaged.',
      ],
      criticalJoints: [
        PoseLandmark.leftShoulder,
        PoseLandmark.rightShoulder,
        PoseLandmark.leftHip,
        PoseLandmark.rightHip,
        PoseLandmark.leftAnkle,
        PoseLandmark.rightAnkle,
      ],
    ),
    'cable_crunch': _profile(
      id: 'cable_crunch',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, 2 m away, mid-torso height.',
      framing: 'Side view: spine curling down and returning upright.',
      safety: 'Curl from the abs, not the arms.',
      steps: [
        'Kneel facing away from the camera, side profile visible.',
        'Crunch ribs toward hips.',
        'Return to a tall kneeling position.',
      ],
      joints: [
        PoseLandmark.leftShoulder,
        PoseLandmark.rightShoulder,
        PoseLandmark.leftHip,
        PoseLandmark.rightHip,
      ],
      rep: _defaultRep,
    ),
    'leg_raise': _profile(
      id: 'leg_raise',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, floor level, full legs in frame.',
      framing: 'Side view: legs lifting toward the chest.',
      safety: 'Keep lower back pressed down if on the floor.',
      steps: [
        'Lie on your back, side to camera.',
        'Legs extended on the ground at the start.',
        'Raise legs until hips flex clearly, then lower.',
      ],
      joints: _hipLeg,
      rep: _defaultRep,
    ),
    'bicycle_crunch': _profile(
      id: 'bicycle_crunch',
      orientation: CameraOrientationHint.front,
      placement: 'Phone above you or in front at floor level, full torso visible.',
      framing: 'Front view: alternating elbow toward opposite knee.',
      safety: 'Move slowly; rotate through the torso.',
      steps: [
        'Lie on your back, face the camera.',
        'Bring opposite elbow toward knee.',
        'Alternate sides each rep.',
      ],
      joints: _fullBody,
      rep: _defaultRep,
    ),
    'burpee': _profile(
      id: 'burpee',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to the side, 3 m away, full body in frame.',
      framing: 'Side view: squat down, plank, then jump or stand.',
      safety: 'Land softly; step back if needed.',
      steps: [
        'Stand profile to camera.',
        'Squat and place hands on the floor.',
        'Jump or step feet back to plank, then return and stand.',
      ],
      joints: _fullBody,
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 90,
        defaultTop: 160,
        hysteresisBand: 12,
        minRomSpan: 35,
      ),
    ),
    'mountain_climber': _profile(
      id: 'mountain_climber',
      orientation: CameraOrientationHint.side,
      placement: 'Phone low, side view, 2–3 m away.',
      framing: 'Side view: high plank with knees driving forward alternately.',
      safety: 'Shoulders stacked over wrists.',
      steps: [
        'High plank, side to camera.',
        'Drive one knee toward the chest.',
        'Alternate legs — each full cycle counts reps in pairs.',
      ],
      joints: _fullBody,
      rep: _defaultRep,
    ),
    'jump_rope': _profile(
      id: 'jump_rope',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front, full body including feet, 2–3 m away.',
      framing: 'Front view: small vertical hops with feet leaving the floor.',
      safety: 'Stay on the balls of the feet; relax wrists.',
      steps: [
        'Face the camera with rope length set.',
        'Hop lightly — both feet leave the ground each rep.',
        'Keep elbows close to the ribs.',
      ],
      joints: _hipLeg,
      rep: const AdaptiveRepEngineConfig(
        defaultBottom: 0,
        defaultTop: 50,
        hysteresisBand: 6,
        minRomSpan: 8,
      ),
    ),
    'stationary_bike': _profile(
      id: 'stationary_bike',
      orientation: CameraOrientationHint.side,
      placement: 'Phone to your side, knee height, capturing legs on the pedals.',
      framing: 'Side view: knees and hips cycling (upper body optional).',
      safety: 'Adjust seat height; maintain steady cadence.',
      steps: [
        'Sit on the bike, side profile to the camera.',
        'Pedal at a steady rhythm.',
        'Each full down-up knee cycle counts as one rep.',
      ],
      joints: _hipLeg,
      rep: _defaultRep,
    ),
    'jumping_jacks': _profile(
      id: 'jumping_jacks',
      orientation: CameraOrientationHint.front,
      placement: 'Phone in front, full body, 2–3 m away.',
      framing: 'Front view: arms and legs opening and closing together.',
      safety: 'Land softly with slightly bent knees.',
      steps: [
        'Stand facing the camera, feet together.',
        'Jump feet out while raising arms overhead.',
        'Return to the start position.',
      ],
      joints: [..._upperBody, PoseLandmark.leftAnkle, PoseLandmark.rightAnkle],
      rep: _defaultRep,
    ),
  };

  static ExerciseProfile _profile({
    required String id,
    required CameraOrientationHint orientation,
    required String placement,
    required String framing,
    required String safety,
    required List<String> steps,
    required List<PoseLandmark> joints,
    AdaptiveRepEngineConfig? rep,
  }) {
    return ExerciseProfile(
      id: id,
      mode: ExerciseTrackingMode.repBased,
      preferredLens: CameraLensDirection.front,
      orientationHint: orientation,
      placementHint: placement,
      framingHint: framing,
      safetyNote: safety,
      setupSteps: steps,
      criticalJoints: joints,
      repConfig: rep,
    );
  }
}
