import json
import re
from pathlib import Path

root = Path(__file__).resolve().parents[1]
en = json.loads((root / "l10n/app_en.arb").read_text(encoding="utf-8"))
ru_dart = (root / "lib/l10n/app_localizations_ru.dart").read_text(encoding="utf-8")

extracted: dict[str, str] = {}
for m in re.finditer(r"String get (\w+) => '([^']*)';", ru_dart):
    extracted[m.group(1)] = m.group(2)
for m in re.finditer(r"String get (\w+) =>\s*\n\s*'([^']*)';", ru_dart):
    extracted[m.group(1)] = m.group(2)

overrides = {
    "navFeed": "Лента",
    "navMap": "Карта",
    "navLeaderboard": "Рейтинг",
    "leaderboardSubtitle": "Рейтинг по захваченной территории на карте",
    "leaderboardYou": "Вы",
    "homeTabDashboard": "Обзор",
    "homeTabWorkouts": "Тренировки",
    "homeMyTraining": "Мои тренировки",
    "homeTrainingSchedule": "Расписание",
    "homeMore": "Ещё",
    "homeFeaturedEmptyTitle": "Нет планов",
    "homeFeaturedEmptySubtitle": "Создайте первую тренировку",
    "homeScreenTitle": "Тренировки",
    "homeCompletedSessions": "{count} завершённых сессий",
    "minutesShort": "{count} мин",
    "durationMinutesLabel": "{count} мин",
    "exercisesCount": "{count} упр.",
    "exercisesSelected": "Выбрано: {count}",
    "homeAddWorkout": "Добавить тренировку",
    "workoutListEmptyTitle": "Список тренировок пуст",
    "workoutListEmptyBody": "Создайте тренировку с упражнениями на новый день.",
    "workoutAddTrainingDay": "Добавить день",
    "workoutChooseMuscleGroup": "Выберите группу мышц",
    "workoutChooseExercises": "Выберите упражнения",
    "workoutNameYourWorkout": "Название тренировки",
    "workoutMuscleGroupHint": "Выберите одну или несколько зон для тренировки.",
    "workoutContinue": "Продолжить",
    "workoutContinueGroups": "Продолжить ({count} групп)",
    "workoutSelectExercises": "Выберите упражнения",
    "workoutContinueExercises": "Продолжить ({count})",
    "workoutSaveWorkout": "Сохранить тренировку",
    "workoutExerciseHintSingle": "Упражнения для «{category}». Нажмите на карточку, чтобы выбрать и прочитать описание.",
    "workoutExerciseHintMulti": "Выберите упражнения из выбранных групп мышц.",
    "workoutNameHint": "Введите название…",
    "workoutSelected": "Выбрано",
    "workoutBack": "Назад",
    "planRepeatWorkout": "Повторить тренировку",
    "planCustomizeRepeat": "Настроить и запланировать",
    "planCompletedHint": "Тренировка завершена. Повторите в другой день или измените упражнения.",
    "copyPlanTitle": "Запланировать на другой день",
    "copyPlanConfirm": "Запланировать",
    "snackbarPlanCopied": "Тренировка добавлена в календарь",
    "sessionCaloriesUnit": "{count} ккал",
    "labelRest": "Отдых",
    "historySetsRepsDetail": "{sets} подх. · {reps} повт.",
    "sessionSummaryVolumeLine": "Объём упражнений: {logKcal} ккал · Итого за сессию: {totalKcal} ккал",
    "sessionDurationSecondsOnly": "{count} с",
    "sessionDurationMinutesOnly": "{count} мин",
    "sessionDurationMinutesSeconds": "{minutes} мин {seconds} с",
    "progressTotalSessions": "Всего сессий",
    "progressWeeklyMinutes": "Время за неделю",
    "progressWeeklyCalories": "Калории за неделю",
    "progressWeekActivity": "Калории по дням",
    "progressWeekActivityHint": "Сожжённые калории по дням недели",
    "progressMonthSessions": "Сессий в месяце",
    "progressPlannedUpcoming": "Предстоящие",
    "progressStreakDays": "{count} дн.",
    "progressWeeklyBarsDow1": "П",
    "progressWeeklyBarsDow2": "В",
    "progressWeeklyBarsDow3": "С",
    "progressWeeklyBarsDow4": "Ч",
    "progressWeeklyBarsDow5": "П",
    "progressWeeklyBarsDow6": "С",
    "progressWeeklyBarsDow7": "В",
    "calendarDow1": "П",
    "calendarDow2": "В",
    "calendarDow3": "С",
    "calendarDow4": "Ч",
    "calendarDow5": "П",
    "calendarDow6": "С",
    "calendarDow7": "В",
    "feedSubtitle": "Фото прогресса и записи о тренировках",
    "feedPost": "Пост",
    "feedPublish": "Опубликовать",
    "feedDeletePost": "Удалить пост",
    "feedBlockUser": "Заблокировать",
    "feedReportPost": "Пожаловаться",
    "profileTitle": "Профиль",
    "profileTabPhotos": "Фото",
    "profileTabAbout": "О себе",
    "profileTabFeed": "Лента",
    "profileTabSaved": "Сохранённое",
    "profileTabSettings": "Настройки",
    "profileEditShort": "Изменить",
    "profileClose": "Закрыть",
    "profileNoBio": "Публичное описание пока пустое.",
    "profileAboutEmpty": "Пользователь ещё не добавил информацию о себе.",
    "profilePhotosEmpty": "Пользователь ещё не добавил фото.",
    "profilePostsEmpty": "Пользователь ещё не опубликовал посты.",
    "profileSavedEmpty": "Нет сохранённых постов. Нажмите закладку в ленте, чтобы сохранить.",
    "profilePrivateNotes": "Личные заметки",
    "profilePrivateNotesEmpty": "Добавьте заметки, видимые только вам.",
    "profileFitnessSummary": "Сводка",
    "profileEditProfile": "Редактировать профиль",
    "profileRemindersTitle": "Напоминания о тренировках",
    "profileRemindersSubtitle": "Уведомления о предстоящих занятиях",
    "profileLogOut": "Выйти",
    "languageTitle": "Язык",
    "mapTitle": "Карта территорий",
    "mapLocateMe": "Моё местоположение",
    "mapLocating": "Определяем местоположение…",
    "mapLocationUnavailable": "Не удалось найти вас. Включите GPS и попробуйте снова.",
    "mapLocationServiceDisabled": "Геолокация выключена. Включите GPS, чтобы видеть себя на карте.",
    "mapLocationPermissionDenied": "Нужен доступ к геолокации для отображения на карте.",
    "mapLocationTimeout": "GPS отвечает слишком долго. Выйдите на открытое место и нажмите снова.",
    "mapOpenLocationSettings": "Открыть настройки",
    "mapModeMap": "Карта",
    "mapModeSatellite": "Спутник",
    "mapLeaderboard": "Рейтинг",
    "mapStartCapture": "Начать захват",
    "mapCaptureActive": "Запись маршрута",
    "mapElapsed": "Прошло",
    "mapDistance": "Дистанция",
    "mapEstimatedArea": "Площадь (оценка)",
    "mapGpsAccuracy": "Точность GPS",
    "mapFinishCapture": "Завершить",
    "mapPermissionTitle": "Нужен доступ к геолокации",
    "mapPermissionBody": "GymCoach использует геолокацию, пока приложение открыто, чтобы показывать вас на карте и записывать маршруты захвата.",
    "mapPermissionServiceDisabled": "Включите геолокацию в настройках системы для карты территорий.",
    "mapAllowLocation": "Разрешить геолокацию",
    "mapOpenSettings": "Открыть настройки",
    "mapPermissionDialogTitle": "Включите геолокацию для захвата",
    "mapPermissionDialogBody": "GPS используется только во время активного захвата. Маршрут отправляется на сервер после завершения.",
    "mapContinue": "Продолжить",
    "mapSatelliteUnavailable": "Спутниковый вид требует платного провайдера карт. Бесплатно доступна стандартная карта OpenFreeMap.",
    "mapEmptyTerritories": "Территории ещё не захвачены",
    "mapGpsAccuracyWarning": "Точность GPS ниже нормы. Можно продолжить, но лучше выйти под открытое небо.",
    "mapNameTerritoryTitle": "Назовите территорию",
    "mapTerritoryNameLabel": "Название территории",
    "mapCaptureSuccessTitle": "Территория захвачена",
    "mapDone": "Готово",
    "mapValidationMinPoints": "Запишите минимум 4 точки GPS перед завершением.",
    "mapValidationMinArea": "Площадь слишком мала. Пройдите больший маршрут и попробуйте снова.",
    "mapCaptureFailed": "Не удалось завершить захват. Попробуйте снова.",
    "mapOwner": "Владелец",
    "mapArea": "Площадь",
    "mapCapturedOn": "Захвачено",
    "mapZoomToTerritory": "Показать территорию",
    "mapMyTerritory": "Моя территория",
    "mapLeaderboardTitle": "Рейтинг территорий",
    "mapLeaderboardEmpty": "Данных рейтинга пока нет.",
}
extracted.update(overrides)

ru: dict[str, object] = {"@@locale": "ru"}
for key, value in en.items():
    if key.startswith("@@"):
        continue
    if key.startswith("@"):
        ru[key] = value
    elif key in overrides:
        ru[key] = overrides[key]
    elif key in extracted and "{" not in extracted[key]:
        ru[key] = extracted[key]
    else:
        ru[key] = value

(root / "l10n/app_ru.arb").write_text(
    json.dumps(ru, ensure_ascii=False, indent=2) + "\n",
    encoding="utf-8",
)
